# Changes here will be overwritten by Copier
_commit: v0.0.5-21-gbe4ec60
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
description: Managing an AWS Organization
python_ci_versions:
- 3.12.7
python_version: 3.12.7
repo_name: copier-aws-organization
ssh_port_number: 54184
template_uses_pulumi: true
template_uses_python: true

